---
default:
  image: mcr.microsoft.com/devcontainers/cpp:1-debian-12

stages:
  - build
  - test
  - deploy

include:
   - template: Jobs/Code-Quality.gitlab-ci.yml

build-project:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - ./tools/build-project.sh
  artifacts:
    paths:
      - build/bin
    expire_in: 1 week

build-unit-tests:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - ./tools/build-unit-tests.sh
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build-documentation:
  stage: build
  before_script:
    - git submodule update --init --recursive
    - apt update && apt install -y doxygen
  script:
    - ./tools/build-documentation.sh
  artifacts:
    paths:
      - build/docs
    expire_in: 1 week

code_quality:
  when: manual

run-unit-tests:
  stage: test
  before_script:
    - apt update && apt install -y gcovr
  script:
    - ./build/gcc-coverage/bin/calculate_test --gtest_output="xml:test-report-gcc.xml"
    - gcovr -f src . --root ./ --exclude-unreachable-branches --xml-pretty --print-summary -o "coverage-gcc.xml"
    - mkdir -p build/gcov-html-gcc
    - gcovr -f src . --root ./ --exclude-unreachable-branches --html --html-details -o "build/gcov-html-gcc/index.html"
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    expire_in: 1 week
    reports:
      junit: test-report-gcc.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage-gcc.xml

pages:
  stage: deploy
  script:
    - mv build/docs/ public/
  artifacts:
    paths:
      - public/
